/* ============================================================
 * 固定搭配规则库（数据层，可独立维护）
 * ------------------------------------------------------------
 * 供 web/app.js 消费。老师可以直接编辑本文件扩充规则，
 * 不需要改动 app.js，也无需联网 / 无需任何 API。
 *
 * 1) CLOZE_COLLOCATIONS —— 具体搭配词典（推荐优先扩充这里）
 *    格式：{ p: "take care of", zh: "照顾" }
 *    · p 必须是 3 个词及以上（2 词搭配无法安全判定，会误伤）
 *    · 用 * 代表「任意一词」，用于 one's / sb / sth 这类占位
 *      例："to * surprise" 可匹配 to his surprise / to my surprise
 *    · 匹配时会做词形还原：made->make、went->go、is->be
 *
 * 2) CLOZE_PATTERN_RULES —— 句型 / 结构规则（正则兜底）
 *    格式：{ name, type, structure, pattern, dual }
 *    · pattern 在「空格所在句」上匹配，空位用 ____ 表示
 *    · dual: true 表示既是搭配也要结合上下文线索 → 判为「双路径」
 *    · 越具体的规则越要放在前面（按数组顺序取第一个命中）
 *
 * 3) CLOZE_LEMMA_MAP —— 不规则动词还原表（可扩充）
 * ============================================================ */

/* ---------------- 1. 具体搭配词典 ---------------- */
window.CLOZE_COLLOCATIONS = [
  /* ===== 动词短语：take / make ===== */
  { p: "take care of", zh: "照顾" },
  { p: "take part in", zh: "参加" },
  { p: "take pride in", zh: "以…为傲" },
  { p: "take notice of", zh: "注意到" },
  { p: "take advantage of", zh: "利用" },
  { p: "take charge of", zh: "负责" },
  { p: "take hold of", zh: "抓住" },
  { p: "take the place of", zh: "取代" },
  { p: "take a look at", zh: "看一看" },
  { p: "take a walk", zh: "散步" },
  { p: "take a rest", zh: "休息" },
  { p: "take a seat", zh: "就座" },
  { p: "take a bus", zh: "乘公交车" },
  { p: "take a taxi", zh: "乘出租车" },
  { p: "take a train", zh: "乘火车" },
  { p: "take a plane", zh: "乘飞机" },
  { p: "take a photo", zh: "拍照" },
  { p: "take a picture", zh: "拍照" },
  { p: "take a shower", zh: "洗澡" },
  { p: "take a bath", zh: "洗澡" },
  { p: "take a risk", zh: "冒险" },
  { p: "take a chance", zh: "碰运气" },
  { p: "take a break", zh: "休息一下" },
  { p: "take a deep breath", zh: "深呼吸" },
  { p: "take a trip", zh: "去旅行" },
  { p: "take a message", zh: "捎口信" },
  { p: "take an exam", zh: "参加考试" },
  { p: "take a test", zh: "参加测验" },
  { p: "take * advice", zh: "采纳某人的建议" },
  { p: "take * temperature", zh: "量体温" },
  { p: "take * time", zh: "慢慢来，不着急" },
  { p: "take it easy", zh: "别紧张" },
  { p: "take the medicine", zh: "服药" },
  { p: "make friends with", zh: "与…交朋友" },
  { p: "make a decision", zh: "做决定" },
  { p: "make a deal", zh: "达成约定" },
  { p: "make a mistake", zh: "犯错" },
  { p: "make a living", zh: "谋生" },
  { p: "make up * mind", zh: "下定决心" },
  { p: "make fun of", zh: "取笑" },
  { p: "make use of", zh: "利用" },
  { p: "make a difference", zh: "有影响，起作用" },
  { p: "make a noise", zh: "制造噪音" },
  { p: "make a face", zh: "做鬼脸" },
  { p: "make the bed", zh: "整理床铺" },
  { p: "make a plan", zh: "制定计划" },
  { p: "make a promise", zh: "许诺" },
  { p: "make a speech", zh: "发表演讲" },
  { p: "make an effort", zh: "作出努力" },
  { p: "make room for", zh: "给…腾地方" },
  { p: "make * way", zh: "前进，前往" },
  { p: "make a fire", zh: "生火" },
  { p: "make a call", zh: "打电话" },
  { p: "make a list", zh: "列清单" },
  { p: "make sense of", zh: "弄懂" },

  /* ===== 动词短语：look / get / come / go ===== */
  { p: "look forward to", zh: "期待" },
  { p: "look down on", zh: "看不起" },
  { p: "look down upon", zh: "看不起" },
  { p: "look up to", zh: "尊敬，仰慕" },
  { p: "look out of", zh: "向…外看" },
  { p: "look the same", zh: "看起来一样" },
  { p: "get along with", zh: "与…相处" },
  { p: "get on with", zh: "与…相处；继续做" },
  { p: "get ready for", zh: "为…做准备" },
  { p: "get rid of", zh: "摆脱，除去" },
  { p: "get into trouble", zh: "陷入麻烦" },
  { p: "get in touch with", zh: "与…取得联系" },
  { p: "get used to", zh: "习惯于" },
  { p: "get good grades", zh: "取得好成绩" },
  { p: "get in the way", zh: "挡路，妨碍" },
  { p: "get out of", zh: "从…出来；逃避" },
  { p: "come up with", zh: "想出，提出" },
  { p: "come to an end", zh: "结束" },
  { p: "come into being", zh: "形成，产生" },
  { p: "come back to", zh: "回到" },
  { p: "go for a walk", zh: "去散步" },
  { p: "go out for a walk", zh: "出去散步" },
  { p: "go to bed", zh: "上床睡觉" },
  { p: "go to school", zh: "上学" },
  { p: "go to work", zh: "上班" },
  { p: "go on doing", zh: "继续做" },
  { p: "go on with", zh: "继续" },

  /* ===== 动词短语：put / give / turn / keep / pay / catch ===== */
  { p: "put up with", zh: "忍受" },
  { p: "put * heart into", zh: "全身心投入" },
  { p: "give a talk", zh: "做报告" },
  { p: "give * a hand", zh: "帮某人一把" },
  { p: "give * life to", zh: "献身于" },
  { p: "give a call", zh: "打电话" },
  { p: "give * advice", zh: "给某人建议" },
  { p: "turn to * for help", zh: "向某人求助" },
  { p: "keep in touch with", zh: "与…保持联系" },
  { p: "keep up with", zh: "跟上，不落后" },
  { p: "keep on doing", zh: "继续做" },
  { p: "keep a diary", zh: "记日记" },
  { p: "keep a secret", zh: "保守秘密" },
  { p: "keep * word", zh: "守信" },
  { p: "keep the balance", zh: "保持平衡" },
  { p: "pay attention to", zh: "注意" },
  { p: "pay a visit to", zh: "拜访" },
  { p: "catch up with", zh: "赶上" },
  { p: "catch a cold", zh: "感冒" },
  { p: "catch a bus", zh: "赶公交车" },
  { p: "catch sight of", zh: "看见，瞥见" },
  { p: "catch * eye", zh: "引人注目" },

  /* ===== 动词短语：其余高频 ===== */
  { p: "run out of", zh: "用完，耗尽" },
  { p: "run a business", zh: "经营生意" },
  { p: "run a fever", zh: "发烧" },
  { p: "break the rule", zh: "违反规则" },
  { p: "break * heart", zh: "使某人心碎" },
  { p: "break a record", zh: "打破纪录" },
  { p: "find * way", zh: "找到路" },
  { p: "work hard at", zh: "努力学习 / 工作" },
  { p: "set an example", zh: "树立榜样" },
  { p: "show * around", zh: "带某人参观" },
  { p: "hold a meeting", zh: "开会" },
  { p: "hold * breath", zh: "屏住呼吸" },
  { p: "lose * way", zh: "迷路" },
  { p: "remind * of", zh: "使某人想起" },
  { p: "try * best", zh: "尽某人最大努力" },
  { p: "do * best", zh: "尽某人最大努力" },
  { p: "do well in", zh: "在…方面做得好" },
  { p: "do harm to", zh: "对…有害" },
  { p: "do good to", zh: "对…有益" },
  { p: "have a good time", zh: "玩得开心" },
  { p: "have a look at", zh: "看一看" },
  { p: "have a rest", zh: "休息" },
  { p: "have a try", zh: "试一试" },
  { p: "have a cold", zh: "感冒" },
  { p: "have a fever", zh: "发烧" },
  { p: "have a headache", zh: "头痛" },
  { p: "have a toothache", zh: "牙痛" },
  { p: "have fun doing", zh: "做…很开心" },
  { p: "have trouble doing", zh: "做…有困难" },
  { p: "have difficulty doing", zh: "做…有困难" },
  { p: "have an effect on", zh: "对…有影响" },
  { p: "have an influence on", zh: "对…有影响" },
  { p: "have a talk with", zh: "与…交谈" },
  { p: "have a word with", zh: "与…说句话" },
  { p: "spend time doing", zh: "花时间做" },
  { p: "spend money on", zh: "把钱花在…上" },
  { p: "waste time doing", zh: "浪费时间做" },
  { p: "succeed in doing", zh: "成功做成" },
  { p: "dream of doing", zh: "梦想做" },
  { p: "thank * for doing", zh: "感谢某人做了…" },
  { p: "praise * for doing", zh: "表扬某人做了…" },
  { p: "stop * from doing", zh: "阻止某人做" },
  { p: "prevent * from doing", zh: "阻止某人做" },
  { p: "protect * from doing", zh: "保护某人免于" },
  { p: "provide * with", zh: "给某人提供" },
  { p: "fill * with", zh: "用…装满" },
  { p: "compare * with", zh: "把…与…比较" },
  { p: "share * with", zh: "与…分享" },
  { p: "cover * with", zh: "用…覆盖" },
  { p: "introduce * to", zh: "把某人介绍给" },
  { p: "explain * to", zh: "向某人解释" },
  { p: "say hello to", zh: "向…问好" },
  { p: "say goodbye to", zh: "向…道别" },
  { p: "say sorry to", zh: "向…道歉" },
  { p: "apologize to * for", zh: "因…向某人道歉" },

  /* ===== 动名词 / 不定式：动词 + doing ===== */
  { p: "can not help doing", zh: "忍不住做" },
  { p: "can not stand doing", zh: "无法忍受做" },
  { p: "feel like doing", zh: "想要做" },
  { p: "give up doing", zh: "放弃做" },
  { p: "put off doing", zh: "推迟做" },
  { p: "be busy doing", zh: "忙于做" },
  { p: "be worth doing", zh: "值得做" },
  { p: "be used to doing", zh: "习惯于做" },
  { p: "be interested in doing", zh: "对做…感兴趣" },
  { p: "be good at doing", zh: "擅长做" },
  { p: "think about doing", zh: "考虑做" },
  { p: "think of doing", zh: "考虑做" },
  { p: "worry about doing", zh: "担心做" },
  { p: "apologize for doing", zh: "为做…道歉" },
  { p: "be sorry for doing", zh: "为做…感到抱歉" },
  { p: "be famous for doing", zh: "因做…而出名" },

  /* ===== be + 形容词 + 介词 / 不定式 ===== */
  { p: "be good at", zh: "擅长" },
  { p: "be good for", zh: "对…有益" },
  { p: "be good to", zh: "对…友好" },
  { p: "be bad for", zh: "对…有害" },
  { p: "be late for", zh: "迟到" },
  { p: "be famous for", zh: "因…而闻名" },
  { p: "be known for", zh: "因…而闻名" },
  { p: "be ready for", zh: "为…做好准备" },
  { p: "be sorry for", zh: "为…感到抱歉" },
  { p: "be thankful for", zh: "感谢…" },
  { p: "be responsible for", zh: "对…负责" },
  { p: "be fit for", zh: "适合于" },
  { p: "be eager for", zh: "渴望" },
  { p: "be thirsty for", zh: "渴望" },
  { p: "be suitable for", zh: "适合于" },
  { p: "be necessary for", zh: "对…是必要的" },
  { p: "be convenient for", zh: "对…方便" },
  { p: "be famous as", zh: "作为…而闻名" },
  { p: "be known as", zh: "作为…而闻名" },
  { p: "be regarded as", zh: "被视为" },
  { p: "be used as", zh: "被用作" },
  { p: "be used for", zh: "被用于" },
  { p: "be proud of", zh: "以…为傲" },
  { p: "be afraid of", zh: "害怕" },
  { p: "be full of", zh: "充满" },
  { p: "be fond of", zh: "喜欢" },
  { p: "be tired of", zh: "厌倦" },
  { p: "be sure of", zh: "确信" },
  { p: "be careful of", zh: "小心" },
  { p: "be made of", zh: "由…制成(看得出原料)" },
  { p: "be made from", zh: "由…制成(看不出原料)" },
  { p: "be made up of", zh: "由…组成" },
  { p: "be short of", zh: "缺乏" },
  { p: "be aware of", zh: "意识到" },
  { p: "be ashamed of", zh: "为…感到羞愧" },
  { p: "be in charge of", zh: "负责" },
  { p: "be in need of", zh: "需要" },
  { p: "be interested in", zh: "对…感兴趣" },
  { p: "be weak in", zh: "在…方面薄弱" },
  { p: "be rich in", zh: "富含" },
  { p: "be poor in", zh: "在…方面贫乏" },
  { p: "be successful in", zh: "在…方面成功" },
  { p: "be absorbed in", zh: "专注于" },
  { p: "be dressed in", zh: "穿着" },
  { p: "be located in", zh: "位于" },
  { p: "be caught in", zh: "遭遇(雨、雪等)" },
  { p: "be busy with", zh: "忙于" },
  { p: "be strict with", zh: "对…严格" },
  { p: "be angry with", zh: "对…生气" },
  { p: "be pleased with", zh: "对…满意" },
  { p: "be satisfied with", zh: "对…满意" },
  { p: "be patient with", zh: "对…有耐心" },
  { p: "be popular with", zh: "受…欢迎" },
  { p: "be careful with", zh: "小心对待" },
  { p: "be filled with", zh: "充满" },
  { p: "be covered with", zh: "被…覆盖" },
  { p: "be crowded with", zh: "挤满" },
  { p: "be born with", zh: "天生具有" },
  { p: "be honest with", zh: "对…诚实" },
  { p: "be familiar with", zh: "熟悉" },
  { p: "be friendly with", zh: "与…友好" },
  { p: "be different from", zh: "与…不同" },
  { p: "be far from", zh: "远离；远非" },
  { p: "be free from", zh: "免于" },
  { p: "be safe from", zh: "免于…的危险" },
  { p: "be similar to", zh: "与…相似" },
  { p: "be kind to", zh: "对…友好" },
  { p: "be polite to", zh: "对…有礼貌" },
  { p: "be rude to", zh: "对…粗鲁" },
  { p: "be useful to", zh: "对…有用" },
  { p: "be harmful to", zh: "对…有害" },
  { p: "be equal to", zh: "等于；胜任" },
  { p: "be grateful to", zh: "感激…" },
  { p: "be married to", zh: "与…结婚" },
  { p: "be close to", zh: "靠近；接近于" },
  { p: "be open to", zh: "对…开放" },
  { p: "be used to", zh: "习惯于" },
  { p: "be worried about", zh: "担心" },
  { p: "be careful about", zh: "对…小心" },
  { p: "be crazy about", zh: "迷恋" },
  { p: "be excited about", zh: "对…感到兴奋" },
  { p: "be nervous about", zh: "对…紧张" },
  { p: "be sure about", zh: "对…确信" },
  { p: "be amazed at", zh: "对…感到惊讶" },
  { p: "be surprised at", zh: "对…感到惊讶" },
  { p: "be angry at", zh: "对…生气" },
  { p: "be shocked at", zh: "对…感到震惊" },
  { p: "be of great value", zh: "很有价值" },
  { p: "be of great importance", zh: "很重要" },
  { p: "be of great help", zh: "很有帮助" },
  { p: "be of great use", zh: "很有用" },
  { p: "be able to do", zh: "能够做" },
  { p: "be willing to do", zh: "愿意做" },
  { p: "be ready to do", zh: "准备做" },
  { p: "be sure to do", zh: "一定会做" },
  { p: "be certain to do", zh: "确定做" },
  { p: "be likely to do", zh: "可能做" },
  { p: "be eager to do", zh: "渴望做" },
  { p: "be anxious to do", zh: "渴望做" },
  { p: "be determined to do", zh: "决心做" },
  { p: "be supposed to do", zh: "应该做" },
  { p: "be expected to do", zh: "被期望做" },
  { p: "be allowed to do", zh: "被允许做" },
  { p: "be made to do", zh: "被迫做" },
  { p: "be asked to do", zh: "被要求做" },
  { p: "be told to do", zh: "被告知做" },
  { p: "be invited to do", zh: "被邀请做" },
  { p: "be encouraged to do", zh: "被鼓励做" },
  { p: "be advised to do", zh: "被建议做" },
  { p: "be required to do", zh: "被要求做" },
  { p: "be forced to do", zh: "被迫做" },
  { p: "be glad to do", zh: "高兴做" },
  { p: "be happy to do", zh: "开心做" },
  { p: "be sad to do", zh: "难过做" },
  { p: "be surprised to do", zh: "惊讶地做" },
  { p: "be excited to do", zh: "兴奋地做" },
  { p: "be satisfied to do", zh: "满意地做" },
  { p: "be proud to do", zh: "自豪地做" },
  { p: "be ashamed to do", zh: "羞于做" },
  { p: "be careful to do", zh: "小心做" },
  { p: "be afraid to do", zh: "害怕做" },

  /* ===== 介词短语：in / on / at ===== */
  { p: "in front of", zh: "在…前面" },
  { p: "in the front of", zh: "在…前部" },
  { p: "in the middle of", zh: "在…中间" },
  { p: "in the end", zh: "最后" },
  { p: "in a hurry", zh: "匆忙" },
  { p: "in a word", zh: "总之" },
  { p: "in a low voice", zh: "低声地" },
  { p: "in a loud voice", zh: "大声地" },
  { p: "in a gentle voice", zh: "温柔地" },
  { p: "in surprise", zh: "惊讶地" },
  { p: "in danger", zh: "处于危险中" },
  { p: "in trouble", zh: "处于困境" },
  { p: "in need", zh: "需要帮助的" },
  { p: "in return", zh: "作为回报" },
  { p: "in public", zh: "公开地" },
  { p: "in common", zh: "共同" },
  { p: "in fact", zh: "事实上" },
  { p: "in order to", zh: "为了" },
  { p: "in order that", zh: "为了" },
  { p: "in silence", zh: "沉默地" },
  { p: "in person", zh: "亲自" },
  { p: "in advance", zh: "提前" },
  { p: "in addition", zh: "此外" },
  { p: "in general", zh: "一般来说" },
  { p: "in total", zh: "总共" },
  { p: "in charge of", zh: "负责" },
  { p: "in the hope of", zh: "怀着…的希望" },
  { p: "in * opinion", zh: "依某人看" },
  { p: "in * spare time", zh: "在某人的空闲时间" },
  { p: "in * free time", zh: "在某人的空闲时间" },
  { p: "in the past", zh: "在过去" },
  { p: "in the future", zh: "在将来" },
  { p: "in this way", zh: "这样，用这种方法" },
  { p: "in a way", zh: "在某种程度上" },
  { p: "in the way", zh: "挡路，妨碍" },
  { p: "in no way", zh: "决不" },
  { p: "in the sun", zh: "在阳光下" },
  { p: "in the rain", zh: "在雨中" },
  { p: "in the sky", zh: "在天空中" },
  { p: "in the world", zh: "在世界上" },
  { p: "in the countryside", zh: "在乡下" },
  { p: "in the distance", zh: "在远处" },
  { p: "in the north of", zh: "在…北部" },
  { p: "in the south of", zh: "在…南部" },
  { p: "in the east of", zh: "在…东部" },
  { p: "in the west of", zh: "在…西部" },
  { p: "in * eyes", zh: "在某人眼中" },
  { p: "in * heart", zh: "在某人心中" },
  { p: "in * mind", zh: "在某人脑海里" },
  { p: "in * fifties", zh: "在某人五十多岁时" },
  { p: "in * view", zh: "依某人看" },
  { p: "in a moment", zh: "立刻，马上" },
  { p: "in a minute", zh: "立刻，马上" },
  { p: "in the corner", zh: "在角落里" },
  { p: "in the center of", zh: "在…中心" },
  { p: "in good health", zh: "身体健康" },
  { p: "in high spirits", zh: "情绪高涨" },
  { p: "in low spirits", zh: "情绪低落" },
  { p: "on the way", zh: "在路上" },
  { p: "on * way to", zh: "在某人去…的路上" },
  { p: "on the left", zh: "在左边" },
  { p: "on the right", zh: "在右边" },
  { p: "on both sides", zh: "在两边" },
  { p: "on the other hand", zh: "另一方面" },
  { p: "on the one hand", zh: "一方面" },
  { p: "on the contrary", zh: "正相反" },
  { p: "on the phone", zh: "在通电话" },
  { p: "on the radio", zh: "在广播里" },
  { p: "on the Internet", zh: "在网上" },
  { p: "on the computer", zh: "在电脑上" },
  { p: "on purpose", zh: "故意地" },
  { p: "on the top of", zh: "在…顶部" },
  { p: "on the bottom of", zh: "在…底部" },
  { p: "on the edge of", zh: "在…边缘" },
  { p: "on the back of", zh: "在…背面" },
  { p: "at the age of", zh: "在…岁时" },
  { p: "at the end of", zh: "在…末尾" },
  { p: "at the beginning of", zh: "在…开始时" },
  { p: "at the top of", zh: "在…顶部" },
  { p: "at the bottom of", zh: "在…底部" },
  { p: "at the foot of", zh: "在…脚下" },
  { p: "at the same time", zh: "同时" },
  { p: "at the moment", zh: "此刻" },
  { p: "at one time", zh: "曾经，一度" },
  { p: "at a time", zh: "一次" },
  { p: "at any time", zh: "随时" },
  { p: "at all times", zh: "一直，始终" },
  { p: "at this time", zh: "此时" },
  { p: "at that time", zh: "那时" },
  { p: "at first sight", zh: "初见，乍一看" },
  { p: "at a speed of", zh: "以…的速度" },
  { p: "at the price of", zh: "以…的价格" },
  { p: "at the cost of", zh: "以…为代价" },
  { p: "at the risk of", zh: "冒…的风险" },
  { p: "at a loss", zh: "茫然，不知所措" },
  { p: "at a discount", zh: "打折" },
  { p: "at the end", zh: "最后" },

  /* ===== 介词短语：by / for / out of / to / with / without ===== */
  { p: "by the way", zh: "顺便说一下" },
  { p: "by means of", zh: "通过…方式" },
  { p: "by the end of", zh: "到…结束时" },
  { p: "by the time", zh: "到…的时候" },
  { p: "for a while", zh: "一会儿" },
  { p: "for a moment", zh: "一会儿" },
  { p: "for the first time", zh: "第一次" },
  { p: "for the last time", zh: "最后一次" },
  { p: "for the time being", zh: "暂时" },
  { p: "for one thing", zh: "一方面" },
  { p: "for the purpose of", zh: "为了…目的" },
  { p: "for the sake of", zh: "为了…起见" },
  { p: "for the benefit of", zh: "为了…的利益" },
  { p: "for the better", zh: "好转" },
  { p: "for the worse", zh: "恶化" },
  { p: "for lack of", zh: "因缺乏" },
  { p: "for fear of", zh: "以免，生怕" },
  { p: "for the rest of", zh: "其余的" },
  { p: "for the most part", zh: "大部分" },
  { p: "out of order", zh: "出故障" },
  { p: "out of control", zh: "失控" },
  { p: "out of breath", zh: "上气不接下气" },
  { p: "out of date", zh: "过时的" },
  { p: "out of work", zh: "失业" },
  { p: "out of sight", zh: "看不见" },
  { p: "out of mind", zh: "心不在焉" },
  { p: "out of danger", zh: "脱离危险" },
  { p: "out of reach", zh: "够不着" },
  { p: "out of touch", zh: "失去联系" },
  { p: "out of place", zh: "不合适的" },
  { p: "out of the question", zh: "不可能的" },
  { p: "out of fashion", zh: "过时的" },
  { p: "out of curiosity", zh: "出于好奇" },
  { p: "out of kindness", zh: "出于好意" },
  { p: "out of pity", zh: "出于同情" },
  { p: "out of respect", zh: "出于尊敬" },
  { p: "out of fear", zh: "出于恐惧" },
  { p: "out of habit", zh: "出于习惯" },
  { p: "out of interest", zh: "出于兴趣" },
  { p: "to * surprise", zh: "令某人惊讶的是" },
  { p: "to * joy", zh: "令某人高兴的是" },
  { p: "to * delight", zh: "令某人高兴的是" },
  { p: "to * disappointment", zh: "令某人失望的是" },
  { p: "to * relief", zh: "令某人宽慰的是" },
  { p: "to * satisfaction", zh: "令某人满意的是" },
  { p: "to * amazement", zh: "令某人惊奇的是" },
  { p: "to * sorrow", zh: "令某人悲伤的是" },
  { p: "to * regret", zh: "令某人遗憾的是" },
  { p: "to * credit", zh: "值得称赞的是" },
  { p: "with the help of", zh: "在…的帮助下" },
  { p: "with * help", zh: "在某人的帮助下" },
  { p: "with a smile", zh: "微笑着" },
  { p: "with a nod", zh: "点头示意" },
  { p: "with a laugh", zh: "笑着" },
  { p: "with a sigh", zh: "叹着气" },
  { p: "with great care", zh: "非常小心地" },
  { p: "with great difficulty", zh: "非常困难地" },
  { p: "with great pleasure", zh: "非常乐意地" },
  { p: "with great interest", zh: "怀着极大兴趣" },
  { p: "with great effort", zh: "付出巨大努力" },
  { p: "with great courage", zh: "带着巨大勇气" },
  { p: "with great confidence", zh: "满怀信心地" },
  { p: "without doubt", zh: "毫无疑问" },
  { p: "without question", zh: "毫无疑问" },
  { p: "without delay", zh: "立即" },
  { p: "without hesitation", zh: "毫不犹豫" },
  { p: "without fail", zh: "必定，务必" },
  { p: "without exception", zh: "毫无例外" },
  { p: "without difficulty", zh: "毫不费力地" },
  { p: "without permission", zh: "未经允许" },
  { p: "without warning", zh: "毫无预兆地" },

  /* ===== 连词 / 逻辑衔接 ===== */
  { p: "as a result", zh: "结果" },
  { p: "as a result of", zh: "由于" },
  { p: "as soon as", zh: "一…就" },
  { p: "as long as", zh: "只要" },
  { p: "as well as", zh: "以及，和" },
  { p: "as far as", zh: "就…而言" },
  { p: "as a matter of fact", zh: "事实上" },
  { p: "instead of", zh: "代替，而不是" },
  { p: "because of", zh: "因为" },
  { p: "thanks to", zh: "多亏，由于" },
  { p: "due to", zh: "由于" },
  { p: "according to", zh: "根据" },
  { p: "in spite of", zh: "尽管" },
  { p: "regardless of", zh: "不管" },
  { p: "in case of", zh: "万一" },
  { p: "apart from", zh: "除…之外" },
  { p: "except for", zh: "除…之外" },
  { p: "but for", zh: "要不是" },
  { p: "rather than", zh: "而不是" },
  { p: "other than", zh: "除了" },
  { p: "first of all", zh: "首先" },
  { p: "all in all", zh: "总而言之" },
  { p: "all of a sudden", zh: "突然" },
  { p: "all over the world", zh: "全世界" },
  { p: "all the time", zh: "一直" },
  { p: "all the way", zh: "一路上" },
  { p: "all the same", zh: "仍然，照样" },
  { p: "all at once", zh: "突然，同时" },
  { p: "on condition that", zh: "条件是" },
  { p: "now that", zh: "既然" },
  { p: "so that", zh: "以便，结果是" },

  /* ===== 数量 / 限定结构 ===== */
  { p: "a lot of", zh: "许多" },
  { p: "a number of", zh: "若干，许多" },
  { p: "the number of", zh: "…的数量" },
  { p: "a great deal of", zh: "大量" },
  { p: "a great many", zh: "许多" },
  { p: "a large amount of", zh: "大量" },
  { p: "a large quantity of", zh: "大量" },
  { p: "a bit of", zh: "一点" },
  { p: "a couple of", zh: "几个" },
  { p: "a pair of", zh: "一双 / 一副" },
  { p: "a piece of", zh: "一张 / 一块" },
  { p: "a set of", zh: "一套" },
  { p: "a group of", zh: "一群" },
  { p: "a kind of", zh: "一种" },
  { p: "a sort of", zh: "一种" },
  { p: "a type of", zh: "一种" },
  { p: "a variety of", zh: "各种各样的" },
  { p: "a series of", zh: "一系列" },
  { p: "a total of", zh: "总共" },
  { p: "a matter of", zh: "…的问题" },
  { p: "a lack of", zh: "缺乏" },
  { p: "a waste of", zh: "浪费" },
  { p: "hundreds of", zh: "数以百计" },
  { p: "thousands of", zh: "数以千计" },
  { p: "millions of", zh: "数以百万计" },
  { p: "billions of", zh: "数以十亿计" },
  { p: "dozens of", zh: "几十" },
  { p: "scores of", zh: "许多" },
  { p: "one of the", zh: "…之一" },
  { p: "one of them", zh: "他们中的一个" },
  { p: "one of us", zh: "我们中的一个" },
  { p: "one of you", zh: "你们中的一个" },
  { p: "some of the", zh: "其中一些" },
  { p: "most of the", zh: "其中大多数" },
  { p: "many of the", zh: "其中许多" },
  { p: "each of the", zh: "每一个" },
  { p: "both of the", zh: "两个都" },
  { p: "none of the", zh: "没有一个" },
  { p: "all of the", zh: "所有的" },
  { p: "the rest of", zh: "其余的" }
];

/* ---------------- 1b. 两词搭配词典 ---------------- *
 * 两词搭配（give up / in silence / turn off …）去掉一个词后只剩一个锚点，
 * 单独靠上下文无法安全判定，因此匹配时额外要求：
 *   「被挖掉的那个词必须出现在选项里（或就是标准答案）」。
 * 这样既能识别两词搭配，又不会把 "in the morning" 之类误判成固定搭配。
 * --------------------------------------------------- */
window.CLOZE_COLLOCATIONS_2 = [
  /* 短语动词 */
  { p: "give up", zh: "放弃" }, { p: "give in", zh: "屈服" }, { p: "give out", zh: "分发；耗尽" },
  { p: "give away", zh: "赠送；泄露" }, { p: "give back", zh: "归还" }, { p: "give off", zh: "发出(气味/光)" },
  { p: "put on", zh: "穿上；上演" }, { p: "put off", zh: "推迟" }, { p: "put up", zh: "张贴；举起" },
  { p: "put away", zh: "收好" }, { p: "put out", zh: "熄灭" }, { p: "put down", zh: "放下；镇压" },
  { p: "put back", zh: "放回" }, { p: "put forward", zh: "提出" }, { p: "put aside", zh: "搁置；储存" },
  { p: "take off", zh: "脱下；起飞" }, { p: "take up", zh: "开始从事；占据" }, { p: "take out", zh: "取出" },
  { p: "take away", zh: "拿走" }, { p: "take back", zh: "收回" }, { p: "take in", zh: "吸收；欺骗" },
  { p: "take on", zh: "承担；呈现" }, { p: "take over", zh: "接管" }, { p: "take down", zh: "记下；拆下" },
  { p: "turn on", zh: "打开" }, { p: "turn off", zh: "关闭" }, { p: "turn up", zh: "调大；出现" },
  { p: "turn down", zh: "调小；拒绝" }, { p: "turn out", zh: "结果是" }, { p: "turn into", zh: "变成" },
  { p: "turn over", zh: "翻转" }, { p: "turn back", zh: "折回" }, { p: "turn around", zh: "转身" },
  { p: "turn to", zh: "求助于；翻到" }, { p: "turn away", zh: "拒绝…进入" },
  { p: "look after", zh: "照顾" }, { p: "look for", zh: "寻找" }, { p: "look up", zh: "查阅；抬头看" },
  { p: "look out", zh: "当心" }, { p: "look at", zh: "看" }, { p: "look into", zh: "调查" },
  { p: "look over", zh: "仔细检查" }, { p: "look back", zh: "回顾" }, { p: "look like", zh: "看起来像" },
  { p: "look around", zh: "四处看" }, { p: "look ahead", zh: "向前看；展望" },
  { p: "get up", zh: "起床" }, { p: "get on", zh: "上车；进展" }, { p: "get off", zh: "下车" },
  { p: "get back", zh: "回来" }, { p: "get over", zh: "克服；恢复" }, { p: "get out", zh: "出去" },
  { p: "get in", zh: "进入" }, { p: "get away", zh: "离开；逃脱" }, { p: "get lost", zh: "迷路" },
  { p: "get dressed", zh: "穿衣服" }, { p: "get hurt", zh: "受伤" }, { p: "get married", zh: "结婚" },
  { p: "get together", zh: "聚会" }, { p: "get better", zh: "好转" }, { p: "get ready", zh: "准备好" },
  { p: "get tired", zh: "疲倦" }, { p: "get along", zh: "相处；进展" },
  { p: "come back", zh: "回来" }, { p: "come in", zh: "进来" }, { p: "come out", zh: "出来；出版" },
  { p: "come on", zh: "加油；来吧" }, { p: "come over", zh: "过来" }, { p: "come across", zh: "偶然遇到" },
  { p: "come from", zh: "来自" }, { p: "come true", zh: "实现" }, { p: "come up", zh: "走近；被提出" },
  { p: "come down", zh: "下降" }, { p: "come along", zh: "一起来；进展" },
  /* ↓ 中考高频、此前缺失的条目（均来自真实卷子反馈，缺失会导致误判） */
  { p: "think twice", zh: "再三考虑" }, { p: "keep promise", zh: "信守诺言" },
  { p: "break promise", zh: "违背诺言" }, { p: "make promise", zh: "作出承诺" },
  { p: "keep word", zh: "守信" }, { p: "keep record", zh: "保持记录" },
  { p: "tell truth", zh: "说实话" }, { p: "tell lie", zh: "说谎" },
  { p: "take action", zh: "采取行动" }, { p: "take risk", zh: "冒险" },
  { p: "face problem", zh: "面对问题" }, { p: "solve problem", zh: "解决问题" },
  { p: "meet problem", zh: "遇到问题" }, { p: "have chance", zh: "有机会" },
  { p: "go on", zh: "继续；发生" }, { p: "go out", zh: "出去；熄灭" }, { p: "go over", zh: "复习；检查" },
  { p: "go ahead", zh: "前进；请吧" }, { p: "go by", zh: "经过；(时间)流逝" }, { p: "go through", zh: "经历；通过" },
  { p: "go back", zh: "回去" }, { p: "go home", zh: "回家" }, { p: "go abroad", zh: "出国" },
  { p: "go wrong", zh: "出错" }, { p: "go bad", zh: "变质" }, { p: "go away", zh: "走开" },
  { p: "go down", zh: "下降" }, { p: "go up", zh: "上升" }, { p: "go off", zh: "响起；离开" },
  { p: "make up", zh: "编造；化妆；弥补" }, { p: "make out", zh: "辨认出；理解" }, { p: "make sure", zh: "确保" },
  { p: "make sense", zh: "讲得通" }, { p: "make money", zh: "赚钱" }, { p: "make progress", zh: "取得进步" },
  { p: "keep up", zh: "保持；跟上" }, { p: "keep on", zh: "继续" }, { p: "keep out", zh: "不使进入" },
  { p: "keep quiet", zh: "保持安静" }, { p: "keep healthy", zh: "保持健康" }, { p: "keep fit", zh: "保持健康" },
  { p: "keep calm", zh: "保持冷静" }, { p: "keep away", zh: "远离" }, { p: "keep off", zh: "避开" },
  { p: "break down", zh: "出故障；崩溃" }, { p: "break out", zh: "爆发" }, { p: "break into", zh: "闯入" },
  { p: "break up", zh: "分手；解散" }, { p: "carry out", zh: "执行" }, { p: "carry on", zh: "继续" },
  { p: "cut down", zh: "砍倒；削减" }, { p: "cut off", zh: "切断" }, { p: "cut up", zh: "切碎" },
  { p: "find out", zh: "查明" }, { p: "work out", zh: "算出；锻炼" }, { p: "work on", zh: "从事" },
  { p: "set up", zh: "建立" }, { p: "set off", zh: "出发；引爆" }, { p: "set out", zh: "出发；着手" },
  { p: "set free", zh: "释放" }, { p: "pick up", zh: "捡起；接(人)" }, { p: "pick out", zh: "挑选出" },
  { p: "show up", zh: "出现" }, { p: "show off", zh: "炫耀" }, { p: "show around", zh: "带领参观" },
  { p: "grow up", zh: "长大" }, { p: "bring up", zh: "抚养；提出" }, { p: "bring back", zh: "带回；使想起" },
  { p: "bring out", zh: "使显现；出版" }, { p: "call on", zh: "拜访；号召" }, { p: "call up", zh: "打电话；回忆起" },
  { p: "call for", zh: "要求；来找" }, { p: "call back", zh: "回电话" }, { p: "depend on", zh: "依靠；取决于" },
  { p: "care about", zh: "关心" }, { p: "care for", zh: "照顾；喜欢" }, { p: "worry about", zh: "担心" },
  { p: "think about", zh: "考虑" }, { p: "think of", zh: "想到；认为" }, { p: "think over", zh: "仔细考虑" },
  { p: "hear from", zh: "收到…的信" }, { p: "hear of", zh: "听说" }, { p: "hear about", zh: "听说" },
  { p: "listen to", zh: "听" }, { p: "laugh at", zh: "嘲笑" }, { p: "smile at", zh: "对…微笑" },
  { p: "shout at", zh: "对…大喊" }, { p: "shout to", zh: "朝…喊" }, { p: "stare at", zh: "盯着看" },
  { p: "point at", zh: "指着" }, { p: "point to", zh: "指向" }, { p: "point out", zh: "指出" },
  { p: "wait for", zh: "等待" }, { p: "ask for", zh: "请求；要" }, { p: "belong to", zh: "属于" },
  { p: "learn from", zh: "向…学习" }, { p: "learn about", zh: "了解" }, { p: "suffer from", zh: "遭受" },
  { p: "deal with", zh: "处理" }, { p: "agree with", zh: "同意(某人)" }, { p: "agree on", zh: "就…达成一致" },
  { p: "arrive at", zh: "到达(小地方)" }, { p: "arrive in", zh: "到达(大地方)" },
  { p: "hand in", zh: "上交" }, { p: "hand out", zh: "分发" }, { p: "hold on", zh: "等一下；坚持" },
  { p: "join in", zh: "参加" }, { p: "knock at", zh: "敲(门)" }, { p: "knock on", zh: "敲" },
  { p: "lead to", zh: "导致" }, { p: "live on", zh: "以…为生" }, { p: "pass by", zh: "经过" },
  { p: "prepare for", zh: "为…做准备" }, { p: "search for", zh: "搜寻" }, { p: "see off", zh: "送行" },
  { p: "stand for", zh: "代表" }, { p: "stand up", zh: "站起来" }, { p: "stand out", zh: "突出" },
  { p: "stick to", zh: "坚持" }, { p: "succeed in", zh: "在…成功" }, { p: "try on", zh: "试穿" },
  { p: "try out", zh: "试用" }, { p: "use up", zh: "用完" }, { p: "wake up", zh: "醒来" },
  { p: "watch out", zh: "当心" }, { p: "wear out", zh: "穿破；使疲惫" }, { p: "write down", zh: "写下" },
  { p: "write to", zh: "写信给" }, { p: "run away", zh: "逃跑" }, { p: "run after", zh: "追赶" },
  { p: "run into", zh: "偶然遇到" }, { p: "sit down", zh: "坐下" }, { p: "stay up", zh: "熬夜" },
  { p: "talk to", zh: "与…谈话" }, { p: "talk with", zh: "与…交谈" }, { p: "talk about", zh: "谈论" },
  { p: "speak to", zh: "对…说" }, { p: "pay for", zh: "为…付款" }, { p: "send for", zh: "派人去请" },
  { p: "slow down", zh: "减速" }, { p: "speed up", zh: "加速" }, { p: "throw away", zh: "扔掉" },
  { p: "believe in", zh: "相信；信仰" }, { p: "cheer up", zh: "使高兴" }, { p: "clean up", zh: "打扫" },
  { p: "clear up", zh: "整理；放晴" }, { p: "complain about", zh: "抱怨" }, { p: "concentrate on", zh: "专注于" },
  { p: "consist of", zh: "由…组成" }, { p: "contribute to", zh: "有助于；捐献" }, { p: "die of", zh: "死于(内因)" },
  { p: "die from", zh: "死于(外因)" }, { p: "die out", zh: "灭绝" }, { p: "dream of", zh: "梦想" },
  { p: "end up", zh: "最终成为" }, { p: "fall behind", zh: "落后" }, { p: "fall down", zh: "跌倒" },
  { p: "figure out", zh: "弄明白" }, { p: "fill in", zh: "填写" }, { p: "focus on", zh: "集中于" },
  { p: "hang on", zh: "稍等；坚持" }, { p: "hang out", zh: "闲逛" }, { p: "help out", zh: "帮忙摆脱困境" },
  { p: "hurry up", zh: "赶快" }, { p: "insist on", zh: "坚持" }, { p: "let down", zh: "使失望" },
  { p: "lie down", zh: "躺下" }, { p: "move on", zh: "继续前进" }, { p: "operate on", zh: "给…做手术" },
  { p: "participate in", zh: "参加" }, { p: "protect from", zh: "保护…免受" }, { p: "recover from", zh: "从…康复" },
  { p: "refer to", zh: "指的是；查阅" }, { p: "rely on", zh: "依赖" }, { p: "reply to", zh: "回复" },
  { p: "result in", zh: "导致" }, { p: "result from", zh: "由…引起" }, { p: "return to", zh: "返回" },
  { p: "serve as", zh: "充当" }, { p: "settle down", zh: "定居；安定" }, { p: "sign up", zh: "报名" },
  { p: "sort out", zh: "整理；解决" }, { p: "switch off", zh: "关掉" }, { p: "switch on", zh: "打开" },
  { p: "tidy up", zh: "收拾" }, { p: "wipe out", zh: "消灭" },

  /* be + 形容词 + 介词 / 不定式（省略 be） */
  { p: "good at", zh: "擅长" }, { p: "bad at", zh: "不擅长" }, { p: "good for", zh: "对…有益" },
  { p: "bad for", zh: "对…有害" }, { p: "late for", zh: "迟到" }, { p: "ready for", zh: "为…准备好" },
  { p: "sorry for", zh: "为…抱歉" }, { p: "famous for", zh: "因…闻名" }, { p: "known for", zh: "因…闻名" },
  { p: "eager for", zh: "渴望" }, { p: "thirsty for", zh: "渴望" }, { p: "fit for", zh: "适合于" },
  { p: "responsible for", zh: "对…负责" }, { p: "necessary for", zh: "对…必要" }, { p: "grateful for", zh: "感激" },
  { p: "proud of", zh: "以…为豪" }, { p: "afraid of", zh: "害怕" }, { p: "full of", zh: "充满" },
  { p: "fond of", zh: "喜欢" }, { p: "tired of", zh: "厌倦" }, { p: "sure of", zh: "确信" },
  { p: "aware of", zh: "意识到" }, { p: "ashamed of", zh: "为…羞愧" }, { p: "made of", zh: "由…制成" },
  { p: "made from", zh: "由…制成" }, { p: "short of", zh: "缺乏" }, { p: "plenty of", zh: "大量" },
  { p: "interested in", zh: "对…感兴趣" }, { p: "rich in", zh: "富含" }, { p: "weak in", zh: "在…薄弱" },
  { p: "successful in", zh: "在…成功" }, { p: "located in", zh: "位于" }, { p: "caught in", zh: "遭遇" },
  { p: "busy with", zh: "忙于" }, { p: "strict with", zh: "对…严格" }, { p: "angry with", zh: "对…生气" },
  { p: "pleased with", zh: "对…满意" }, { p: "satisfied with", zh: "对…满意" }, { p: "patient with", zh: "对…有耐心" },
  { p: "popular with", zh: "受…欢迎" }, { p: "careful with", zh: "小心对待" }, { p: "filled with", zh: "充满" },
  { p: "covered with", zh: "被…覆盖" }, { p: "crowded with", zh: "挤满" }, { p: "familiar with", zh: "熟悉" },
  { p: "friendly with", zh: "与…友好" }, { p: "wrong with", zh: "…出了问题" },
  { p: "different from", zh: "与…不同" }, { p: "far from", zh: "远离；远非" }, { p: "free from", zh: "免于" },
  { p: "absent from", zh: "缺席" }, { p: "similar to", zh: "与…相似" }, { p: "kind to", zh: "对…友好" },
  { p: "polite to", zh: "对…有礼貌" }, { p: "rude to", zh: "对…粗鲁" }, { p: "useful to", zh: "对…有用" },
  { p: "harmful to", zh: "对…有害" }, { p: "equal to", zh: "等于" }, { p: "grateful to", zh: "感激" },
  { p: "close to", zh: "接近" }, { p: "open to", zh: "对…开放" }, { p: "used to", zh: "过去常常" },
  { p: "next to", zh: "紧挨着" }, { p: "due to", zh: "由于" }, { p: "up to", zh: "多达；取决于" },
  { p: "worried about", zh: "担心" }, { p: "careful about", zh: "对…小心" }, { p: "crazy about", zh: "迷恋" },
  { p: "excited about", zh: "对…兴奋" }, { p: "nervous about", zh: "对…紧张" }, { p: "angry about", zh: "对…生气" },
  { p: "amazed at", zh: "对…惊讶" }, { p: "surprised at", zh: "对…惊讶" }, { p: "shocked at", zh: "对…震惊" },
  { p: "able to", zh: "能够" }, { p: "willing to", zh: "愿意" }, { p: "sure to", zh: "一定" },
  { p: "certain to", zh: "确定" }, { p: "likely to", zh: "可能" }, { p: "eager to", zh: "渴望" },
  { p: "determined to", zh: "决心" }, { p: "supposed to", zh: "应该" }, { p: "expected to", zh: "被期望" },
  { p: "allowed to", zh: "被允许" }, { p: "asked to", zh: "被要求" }, { p: "told to", zh: "被告知" },
  { p: "invited to", zh: "被邀请" }, { p: "encouraged to", zh: "被鼓励" }, { p: "advised to", zh: "被建议" },
  { p: "required to", zh: "被要求" }, { p: "forced to", zh: "被迫" }, { p: "glad to", zh: "高兴" },
  { p: "proud to", zh: "自豪" }, { p: "ashamed to", zh: "羞于" }, { p: "worth doing", zh: "值得做" },
  { p: "busy doing", zh: "忙于做" }, { p: "have to", zh: "不得不" }, { p: "ought to", zh: "应该" },

  /* 介词 / 副词短语 */
  { p: "in silence", zh: "沉默地" }, { p: "in danger", zh: "处于危险中" }, { p: "in trouble", zh: "处于困境" },
  { p: "in need", zh: "需要帮助的" }, { p: "in return", zh: "作为回报" }, { p: "in public", zh: "公开地" },
  { p: "in common", zh: "共同" }, { p: "in fact", zh: "事实上" }, { p: "in time", zh: "及时" },
  { p: "in advance", zh: "提前" }, { p: "in person", zh: "亲自" }, { p: "in short", zh: "简而言之" },
  { p: "in brief", zh: "简言之" }, { p: "in detail", zh: "详细地" }, { p: "in peace", zh: "平静地" },
  { p: "in love", zh: "恋爱中" }, { p: "in hospital", zh: "住院" }, { p: "in bed", zh: "卧床" },
  { p: "in class", zh: "在课堂上" }, { p: "in prison", zh: "坐牢" }, { p: "in line", zh: "排队" },
  { p: "in English", zh: "用英语" }, { p: "in cash", zh: "用现金" }, { p: "in debt", zh: "负债" },
  { p: "in vain", zh: "徒劳" }, { p: "in turn", zh: "依次；反过来" }, { p: "in case", zh: "以防万一" },
  { p: "in charge", zh: "负责" }, { p: "in tears", zh: "流着泪" }, { p: "in fear", zh: "恐惧地" },
  { p: "in pain", zh: "痛苦地" }, { p: "in secret", zh: "秘密地" }, { p: "in surprise", zh: "惊讶地" },
  { p: "in anger", zh: "愤怒地" }, { p: "in joy", zh: "高兴地" }, { p: "in sorrow", zh: "悲伤地" },
  { p: "in excitement", zh: "兴奋地" }, { p: "in relief", zh: "如释重负" }, { p: "in shock", zh: "震惊地" },
  { p: "in despair", zh: "绝望地" }, { p: "in rags", zh: "衣衫褴褛" }, { p: "in ruins", zh: "成为废墟" },
  { p: "in sight", zh: "看得见" }, { p: "in store", zh: "储备着；即将发生" }, { p: "in use", zh: "在使用中" },
  { p: "in view", zh: "在视野内" }, { p: "in addition", zh: "此外" }, { p: "in general", zh: "一般来说" },
  { p: "in total", zh: "总共" }, { p: "on time", zh: "准时" }, { p: "on foot", zh: "步行" },
  { p: "on duty", zh: "值班" }, { p: "on sale", zh: "出售；打折" }, { p: "on show", zh: "展出" },
  { p: "on display", zh: "陈列" }, { p: "on business", zh: "出差" }, { p: "on holiday", zh: "度假" },
  { p: "on vacation", zh: "度假" }, { p: "on purpose", zh: "故意地" }, { p: "on average", zh: "平均" },
  { p: "on fire", zh: "着火" }, { p: "on strike", zh: "罢工" }, { p: "on board", zh: "在船上/飞机上" },
  { p: "on air", zh: "在广播中" }, { p: "on guard", zh: "警戒" }, { p: "on earth", zh: "究竟" },
  { p: "at first", zh: "起初" }, { p: "at last", zh: "最后" }, { p: "at least", zh: "至少" },
  { p: "at most", zh: "至多" }, { p: "at once", zh: "立刻；同时" }, { p: "at present", zh: "目前" },
  { p: "at times", zh: "有时" }, { p: "at night", zh: "在夜里" }, { p: "at noon", zh: "在中午" },
  { p: "at midnight", zh: "在午夜" }, { p: "at dawn", zh: "在黎明" }, { p: "at dusk", zh: "在黄昏" },
  { p: "at work", zh: "在工作" }, { p: "at school", zh: "在上学" }, { p: "at home", zh: "在家" },
  { p: "at war", zh: "处于战争状态" }, { p: "at peace", zh: "处于和平" }, { p: "at ease", zh: "自在" },
  { p: "at hand", zh: "在手边" }, { p: "at best", zh: "充其量" }, { p: "at worst", zh: "最坏情况下" },
  { p: "at all", zh: "根本；完全" }, { p: "at random", zh: "随机地" }, { p: "at church", zh: "在做礼拜" },
  { p: "at sea", zh: "在海上；茫然" }, { p: "by accident", zh: "偶然" }, { p: "by chance", zh: "偶然" },
  { p: "by mistake", zh: "错误地" }, { p: "by hand", zh: "手工" }, { p: "by bus", zh: "乘公交车" },
  { p: "by car", zh: "乘小汽车" }, { p: "by train", zh: "乘火车" }, { p: "by plane", zh: "乘飞机" },
  { p: "by ship", zh: "乘船" }, { p: "by bike", zh: "骑自行车" }, { p: "by air", zh: "乘飞机" },
  { p: "by sea", zh: "乘船" }, { p: "by land", zh: "走陆路" }, { p: "by heart", zh: "凭记忆" },
  { p: "by now", zh: "到现在为止" }, { p: "by then", zh: "到那时" }, { p: "by far", zh: "…得多" },
  { p: "by day", zh: "在白天" }, { p: "by night", zh: "在夜间" }, { p: "by taxi", zh: "乘出租车" },
  { p: "for example", zh: "例如" }, { p: "for instance", zh: "例如" }, { p: "for sure", zh: "确定" },
  { p: "for free", zh: "免费" }, { p: "for sale", zh: "待售" }, { p: "for long", zh: "很久" },
  { p: "for ever", zh: "永远" }, { p: "for nothing", zh: "免费；徒然" }, { p: "for fun", zh: "为了好玩" },
  { p: "for safety", zh: "为了安全" }, { p: "for life", zh: "终身" }, { p: "for years", zh: "多年" },
  { p: "for days", zh: "好几天" }, { p: "for hours", zh: "好几个小时" }, { p: "for now", zh: "暂时" },
  { p: "with pleasure", zh: "乐意地" }, { p: "with care", zh: "小心地" }, { p: "with difficulty", zh: "困难地" },
  { p: "with joy", zh: "高兴地" }, { p: "with pride", zh: "自豪地" }, { p: "with confidence", zh: "自信地" },
  { p: "with patience", zh: "耐心地" }, { p: "with courage", zh: "勇敢地" }, { p: "with kindness", zh: "亲切地" },
  { p: "with interest", zh: "感兴趣地" }, { p: "with success", zh: "成功地" }, { p: "with ease", zh: "轻松地" },
  { p: "with fear", zh: "恐惧地" }, { p: "with respect", zh: "尊敬地" },
  { p: "without doubt", zh: "毫无疑问" }, { p: "without question", zh: "毫无疑问" }, { p: "without delay", zh: "立即" },
  { p: "without fail", zh: "务必" }, { p: "without hesitation", zh: "毫不犹豫" }, { p: "without exception", zh: "毫无例外" },
  { p: "without difficulty", zh: "毫不费力" }, { p: "without warning", zh: "毫无预兆" }, { p: "without permission", zh: "未经允许" },
  { p: "without reason", zh: "毫无理由" }, { p: "without end", zh: "无尽地" },

  /* 其他高频两词结构 */
  { p: "no longer", zh: "不再" }, { p: "no more", zh: "不再" }, { p: "any more", zh: "再；还" },
  { p: "any longer", zh: "再" }, { p: "so that", zh: "以便；结果" }, { p: "even if", zh: "即使" },
  { p: "even though", zh: "即使" }, { p: "as well", zh: "也" }, { p: "as usual", zh: "照常" },
  { p: "as if", zh: "好像" }, { p: "as though", zh: "好像" }, { p: "as for", zh: "至于" },
  { p: "lots of", zh: "许多" }, { p: "all over", zh: "到处" }, { p: "after all", zh: "毕竟" },
  { p: "above all", zh: "最重要的是" }, { p: "first of", zh: "首先" }, { p: "plenty of", zh: "大量" },

  /* 动词 + 名词（中考高频，同样要求「缺词在选项里」才采信） */
  { p: "take place", zh: "发生；举行" }, { p: "take turns", zh: "轮流" }, { p: "take care", zh: "当心" },
  { p: "take action", zh: "采取行动" }, { p: "take notes", zh: "记笔记" }, { p: "take photos", zh: "拍照" },
  { p: "take medicine", zh: "吃药" }, { p: "take exercise", zh: "锻炼" }, { p: "make friends", zh: "交朋友" },
  { p: "make noise", zh: "制造噪音" }, { p: "make trouble", zh: "惹麻烦" }, { p: "make dinner", zh: "做晚饭" },
  { p: "have fun", zh: "玩得开心" }, { p: "have breakfast", zh: "吃早饭" }, { p: "have lunch", zh: "吃午饭" },
  { p: "have supper", zh: "吃晚饭" }, { p: "have dinner", zh: "吃正餐" }, { p: "have class", zh: "上课" },
  { p: "have lesson", zh: "上课" }, { p: "have meeting", zh: "开会" }, { p: "have party", zh: "举行聚会" },
  { p: "have try", zh: "试一试" }, { p: "have look", zh: "看一看" }, { p: "have cold", zh: "感冒" },
  { p: "have fever", zh: "发烧" }, { p: "have rest", zh: "休息" }, { p: "have walk", zh: "散步" },
  { p: "have dream", zh: "做梦" }, { p: "have idea", zh: "有主意" }, { p: "have chance", zh: "有机会" },
  { p: "have time", zh: "有时间" }, { p: "have trouble", zh: "有麻烦" }, { p: "have difficulty", zh: "有困难" },
  { p: "have problem", zh: "有问题" }, { p: "have pity", zh: "同情" },
  { p: "do sports", zh: "做运动" }, { p: "do exercise", zh: "做锻炼/练习" }, { p: "do homework", zh: "做作业" },
  { p: "do housework", zh: "做家务" }, { p: "do shopping", zh: "买东西" }, { p: "do cleaning", zh: "打扫" },
  { p: "tell lies", zh: "说谎" }, { p: "tell truth", zh: "说实话" }, { p: "tell stories", zh: "讲故事" },
  { p: "tell jokes", zh: "讲笑话" }, { p: "lose weight", zh: "减肥" }, { p: "save money", zh: "省钱" },
  { p: "save time", zh: "省时间" }, { p: "waste time", zh: "浪费时间" }, { p: "spend time", zh: "花时间" },
  { p: "earn money", zh: "赚钱" }, { p: "raise hand", zh: "举手" }, { p: "shake hands", zh: "握手" },
  { p: "see doctor", zh: "看医生" }, { p: "watch TV", zh: "看电视" }, { p: "play basketball", zh: "打篮球" },
  { p: "play football", zh: "踢足球" }, { p: "play chess", zh: "下棋" }, { p: "play games", zh: "玩游戏" },
  { p: "ride bike", zh: "骑自行车" }, { p: "fly kite", zh: "放风筝" }, { p: "keep diary", zh: "记日记" },
  { p: "keep secret", zh: "保守秘密" }, { p: "keep promise", zh: "守诺" }, { p: "break promise", zh: "违约" },
  { p: "break record", zh: "打破纪录" }, { p: "win prize", zh: "获奖" }, { p: "lose game", zh: "输掉比赛" },
  { p: "pass exam", zh: "通过考试" }, { p: "fail exam", zh: "考试不及格" }, { p: "attend meeting", zh: "参加会议" },
  { p: "attend class", zh: "上课" }, { p: "join club", zh: "加入社团" }, { p: "join army", zh: "参军" },
  { p: "change mind", zh: "改变主意" }, { p: "draw picture", zh: "画画" }, { p: "sing song", zh: "唱歌" },
  { p: "write letter", zh: "写信" }, { p: "send email", zh: "发邮件" }, { p: "answer question", zh: "回答问题" },
  { p: "ask question", zh: "提问" }, { p: "solve problem", zh: "解决问题" }, { p: "give advice", zh: "给建议" },
  { p: "give chance", zh: "给机会" }, { p: "learn lesson", zh: "吸取教训" }, { p: "teach lesson", zh: "给…一个教训" }

];

/* ---------------- 2. 句型 / 结构规则（正则兜底） ---------------- */
window.CLOZE_PATTERN_RULES = [
  /* ===== A. 具体句型（优先匹配，避免被泛化规则吞掉） ===== */
  { name: "so ... that", type: "结果从句", structure: "so + 形容词/副词 + that 如此…以至于", pattern: /\bso\s+\w+\s+____\b|\bso\s+____\s+that\b/i, dual: false },
  { name: "such ... that", type: "结果从句", structure: "such + (a/an) + 形容词 + 名词 + that", pattern: /\bsuch\s+(?:a\s+|an\s+)?____\s+that\b|\bsuch\s+(?:a|an)\s+\w+\s+____\b/i, dual: false },
  { name: "too ... to", type: "结果结构", structure: "too + 形容词/副词 + to do 太…而不能", pattern: /\btoo\s+\w+\s+____\b|\btoo\s+____\s+to\b/i, dual: false },
  { name: "adj/adv + enough to", type: "结果结构", structure: "形容词/副词 + enough + to do 足够…可以", pattern: /\b____\s+enough\s+to\b|\benough\s+to\s+____/i, dual: false },
  { name: "as ... as", type: "比较结构", structure: "as + 形容词/副词原级 + as 和…一样", pattern: /\bas\s+____\s+as\b/i, dual: true },
  { name: "not so/as ... as", type: "比较结构", structure: "not so/as + 原级 + as 不如…", pattern: /\bso\s+____\s+as\b/i, dual: true },
  { name: "比较级 + than", type: "比较结构", structure: "比较级 + than 比…更", pattern: /\b____\s+than\b|\bmore\s+____\s+than\b/i, dual: true },
  { name: "the + 最高级", type: "比较结构", structure: "the + 最高级 (+ in/of 范围)", pattern: /\bthe\s+____\s+(?:in|among)\b|\bthe\s+____\s+\w+est\b/i, dual: false },
  { name: "the more ... the more", type: "比较结构", structure: "the + 比较级…, the + 比较级 越…越", pattern: /\bthe\s+\w+(?:er|more)\b[^.]*\bthe\s+____/i, dual: false },
  { name: "one of ...", type: "代词结构", structure: "one of + 复数名词/代词 …之一", pattern: /\bone of\s+____/i, dual: true },
  { name: "both ... and", type: "并列结构", structure: "both … and … 既…又", pattern: /\bboth\s+____\s+and\b/i, dual: false },
  { name: "either ... or", type: "并列结构", structure: "either … or … 要么…要么", pattern: /\beither\s+____\s+or\b/i, dual: false },
  { name: "neither ... nor", type: "并列结构", structure: "neither … nor … 既不…也不", pattern: /\bneither\s+____\s+nor\b/i, dual: false },
  { name: "not only ... but also", type: "并列结构", structure: "not only … but also … 不但…而且", pattern: /\bnot only\s+____\s+but\b/i, dual: false },
  { name: "whether ... or", type: "并列结构", structure: "whether … or … 无论…还是", pattern: /\bwhether\s+____\s+or\b/i, dual: false },
  { name: "prefer ... to", type: "比较结构", structure: "prefer A to B 比起 B 更喜欢 A", pattern: /\bprefer\s+____\s+to\b/i, dual: false },
  { name: "would rather ... than", type: "比较结构", structure: "would rather do than do 宁愿…也不", pattern: /\brather\s+____\s+than\b/i, dual: false },
  { name: "not ... until", type: "固定句型", structure: "not … until 直到…才", pattern: /\bnot\s+____\s+until\b|\b____\s+until\b/i, dual: false },
  { name: "not ... any more/longer", type: "固定句型", structure: "not … any more / any longer 不再", pattern: /\b____\s+(?:\w+\s+)?any\s+(?:more|longer)\b|\bno\s+(?:longer|more)\s+____/i, dual: false },
  { name: "hardly ... when", type: "固定句型", structure: "hardly … when 一…就", pattern: /\bhardly\s+____\s+when\b|\b____\s+hardly\b/i, dual: false },
  { name: "no sooner ... than", type: "固定句型", structure: "no sooner … than 一…就", pattern: /\bno\s+sooner\s+____\s+than\b/i, dual: false },
  { name: "used to do", type: "固定句型", structure: "used to do 过去常常", pattern: /\bused\s+____\s+to\b|\bused\s+to\s+____/i, dual: false },
  { name: "it takes ... to do", type: "固定句型", structure: "it takes sb + 时间 + to do 花费…做", pattern: /\btakes?\s+(?:\w+\s+)?____\s+to\b/i, dual: false },
  { name: "spend ... doing / on", type: "固定句型", structure: "spend + 时间/钱 + (in) doing / on sth", pattern: /\bspend\s+\w+\s+(?:____|in\s+____|on\s+____)|\bspent\s+\w+\s+(?:____|in\s+____|on\s+____)/i, dual: false },
  { name: "it is + adj + for/of sb to do", type: "固定句型", structure: "it is + 形容词 + for/of sb + to do", pattern: /\bit\s+(?:is|was)\s+\w+\s+____\s+(?:for|of)\b|\bit\s+(?:is|was)\s+\w+\s+____\s+\w+\s+to\b/i, dual: false },
  { name: "it is + adj + to do", type: "固定句型", structure: "it is + 形容词 + to do 做某事是…的", pattern: /\bit\s+(?:is|was)\s+____\s+to\b/i, dual: false },
  { name: "it is said/reported that", type: "固定句型", structure: "it is said / reported / believed that 据说", pattern: /\bit\s+(?:is|was)\s+____\s+that\b/i, dual: false },
  { name: "there is no doubt that", type: "固定句型", structure: "there is no doubt that 毫无疑问", pattern: /\bthere\s+(?:is|was)\s+____\s+(?:no|nothing|something|little)\b/i, dual: false },
  { name: "it is time to/for", type: "固定句型", structure: "it is time to do / for sth 是…的时候了", pattern: /\btime\s+____\s+(?:to|for)\b|\btime\s+(?:to|for)\s+____/i, dual: false },
  { name: "it is one's turn to do", type: "固定句型", structure: "it is one's turn to do 轮到某人做", pattern: /\bturn\s+____\s+to\b|\b____\s+turn\s+to\b/i, dual: false },
  { name: "had better do", type: "固定句型", structure: "had better (not) do 最好(不)做", pattern: /\bbetter\s+____/i, dual: false },
  { name: "why not do", type: "固定句型", structure: "why not do 为什么不做", pattern: /\bwhy\s+not\s+____/i, dual: false },
  { name: "what/how about doing", type: "固定句型", structure: "what/how about doing …怎么样", pattern: /\b(?:what|how)\s+about\s+____/i, dual: false },
  { name: "would you mind doing", type: "固定句型", structure: "would you mind doing 你介意做…吗", pattern: /\bmind\s+____/i, dual: false },
  { name: "can't wait to do", type: "固定句型", structure: "can't wait to do 迫不及待做", pattern: /\bwait\s+____\s+to\b/i, dual: false },
  { name: "can't help doing", type: "固定句型", structure: "can't help doing 忍不住做", pattern: /\b(?:can'?t|couldn'?t|can\s+not|could\s+not)\s+help\s+____/i, dual: false },
  { name: "let's do", type: "固定句型", structure: "let's do 让我们做", pattern: /\blet(?:'s| us)\s+____/i, dual: false },
  { name: "keep/stop/prevent ... from doing", type: "固定句型", structure: "keep/stop/prevent sb from doing 阻止某人做", pattern: /\bfrom\s+____\s+\w+ing\b|\b(?:stop|stops|stopped|prevent|prevents|prevented|keep|keeps|kept|protect|protects|protected)\s+\w+\s+from\s+____/i, dual: false },
  { name: "have difficulty/trouble (in) doing", type: "固定句型", structure: "have difficulty/trouble (in) doing 做…有困难", pattern: /\b(?:difficulty|trouble|problem|fun|experience)\s+(?:in\s+)?____/i, dual: false },
  { name: "感叹句 what/how", type: "固定句型", structure: "what + (a/an) + 形容词 + 名词 / how + 形容词", pattern: /\bwhat\s+(?:a|an)\s+____|\bhow\s+____\s+(?:a|an|the)\b/i, dual: false },

  /* ===== B. 动词 + 空 + 介词/小品词（短语动词，空在小品词位） ===== */
  { name: "短语动词（空在小品词位）", type: "动词短语",
    structure: "动词 + 空 + 介词/副词小品词（give up / turn off / put on / take off / look at …）；已排除 be 动词与功能词，避免误判",
    pattern: /\b(?!to\b|for\b|of\b|in\b|on\b|at\b|with\b|by\b|from\b|as\b|and\b|or\b|but\b|the\b|a\b|an\b|this\b|that\b|these\b|those\b|it\b|he\b|she\b|they\b|we\b|you\b|i\b|his\b|her\b|my\b|your\b|our\b|their\b|its\b|is\b|are\b|was\b|were\b|be\b|been\b|being\b|am\b|not\b|no\b|so\b|if\b|than\b|which\b|who\b|what\b|when\b|where\b|how\b|because\b|though\b|although\b|while\b|before\b|after\b|since\b|until\b|like\b|such\b)\w+\s+____\s+(?:at|in|of|with|about|for|to|from|on|after|up|off|out|away|down|back|over|through|into|by|against|without|before|behind|under|above|below|around|upon|the|a|an|this|that|these|those|my|your|his|her|their|our|its|some|any|no|him|her|me|us|them|you|it|himself|herself|themselves)\b/i,
    dual: true },

  /* ===== B2. 常见动介动词 + 空 + 介词（laugh at / listen to / wait for 等） =====
     这些动词后的空几乎一定是介词；\w* 兼容 laughed / laughing / laughs 等时态。
     标为双路径：即使偶有误判，学生选「按线索词」也不会被判错。 */
  { name: "动介动词 + 介词", type: "动词短语",
    structure: "laugh at / smile at / listen to / wait for / look at / deal with / belong to / depend on / arrive at / agree with / think about / worry about / care about / hear from / learn from / suffer from / apologize to / thank …",
    pattern: /\b(?:laugh|smile|shout|point|look|listen|wait|ask|care|worry|think|hear|learn|suffer|depend|deal|agree|arrive|belong|talk|speak|believe|dream|complain|apologize|thank|praise|search|prepare|knock|call)\w*\s+____\s+\w+/i,
    dual: true },

  /* ===== C. be + 形容词 + 空（空在介词位） ===== */
  { name: "be + 形容词 + 介词", type: "形容词短语",
    structure: "be + 形容词 + 介词（good at / interested in / proud of / afraid of / late for / different from / strict with …）",
    pattern: /\b(?:am|is|are|was|were|be|been|being|'m|'s|'re|feel|felt|seem|seemed|look|looked|sound|sounded|get|got|become|became|stay|stayed)\s+(?!to\b|not\b|so\b|very\b|too\b|quite\b|also\b|still\b|just\b|only\b|always\b|never\b|really\b|more\b|most\b|the\b|a\b|an\b|and\b|or\b|but\b|there\b|here\b|about\b|going\b)\w+\s+____\b(?!\s*(?:than|as)\b)/i,
    dual: false },

  /* ===== D. be + 空 + 介词（空在形容词位） ===== */
  { name: "be + 形容词 + 介词（空在形容词）", type: "形容词短语",
    structure: "be + ____ + 介词（good/interested/proud/afraid/full/late/famous/ready/known/strict/pleased/busy …）",
    pattern: /\b(?:am|is|are|was|were|be|been|being|'m|'s|'re)\s+____\s+(?:at|in|of|with|about|for|to|from|on|after)\b/i,
    dual: false },

  /* ===== E. 名词 + 介词（空在介词或名词位） ===== */
  { name: "名词 + 介词搭配", type: "名词短语",
    structure: "名词 + 介词（answer/key/way/ticket/solution to；reason/price/cause/chance for；a piece/pair/kind/lot/number of）",
    pattern: /\b(?:answer|key|way|ticket|solution|reply|response|attitude|approach|visit|trip|journey|letter|note|invitation|introduction|entrance|exit|door|road|path|bridge|memory|reason|price|cause|excuse|need|hope|chance|cost|piece|pair|kind|sort|type|lot|number|couple|group|glass|cup|bowl|bottle|box|set)\b\s+____\s+\w+/i,
    dual: false },

  /* ===== F. 介词 + (冠词) + 空（介词短语，空在名词/形容词位） ===== */
  { name: "介词短语", type: "介词短语",
    structure: "介词 + (冠词/物主代词) + 名词（in front of / on time / with the help of / in danger / at night / by accident …）",
    pattern: /\b(?:in|on|at|by|with|for|of|from|to|about|without|under|over|through|into)\s+(?:the|a|an|my|your|his|her|their|our|this|that|these|those|some|any|no|its)\s+____\b|\b____\s+(?:later|ago|before|after|long|soon|now|then|night|once|first|last|least|most|present|fact|return|surprise|peace|need|danger|trouble|public|common|order|time|english|hurry|way|purpose|accident|hand|result|addition|end|all|front|top|bottom|beginning|moment|side|corner|center|middle|head|foot|back|left|right|week|month|year|morning|afternoon|evening|day)\b/i,
    dual: true },

  /* ===== G. 情态动词 + 空（动词原形，仅作提示，走双路径） ===== */
  { name: "情态动词 + 动词原形", type: "动词搭配",
    structure: "can/may/must/should/will 等情态动词后接动词原形",
    pattern: /\b(?:can|could|may|might|must|shall|should|will|would)\s+____\b/i,
    dual: true },

  /* ===== H. 过渡语 / 衔接词（整句命中即算固定搭配） ===== */
  { name: "过渡语 / 衔接词", type: "固定短语",
    structure: "at first / at last / in fact / after all / above all / on the contrary / as a result / in addition / what's more / for example / such as / from now on / in the end",
    pattern: /\b(?:at first|at last|in fact|after all|above all|on the contrary|as a result|in addition|what's more|for example|such as|from now on|sooner or later|in the end|at the same time)\b/i,
    dual: false },

  /* ===== I. 空在功能词之前的结构（空格先于句型词出现） =====
     这类常被误判成别的固定搭配（如 make a mistake），故放最后且尽量收紧。 */
  { name: "too ... to（空在 too 前）", type: "结果结构",
    structure: "be ____ too + 形容词 + to do（空填 too），too 出现在空格之后",
    pattern: /\bwere\s+____\s+too\s+\w+\s+to\b/i, dual: false },
  { name: "make sth come true（空在宾语后）", type: "动词短语",
    structure: "make + (one's) + dream/plan/hope + 空（空填 come true），使…实现",
    pattern: /\bmake\s+(?:our|his|her|their|my|your|the|a\s+)?\s*dream\s+____\b/i, dual: false }
];

/* ---------------- 3. 不规则动词还原表（用于提升命中率） ---------------- */
window.CLOZE_LEMMA_MAP = {
  am: "be", is: "be", are: "be", was: "be", were: "be", been: "be", being: "be", "'s": "be", "'re": "be", "'m": "be",
  has: "have", had: "have", having: "have",
  does: "do", did: "do", done: "do",
  goes: "go", went: "go", gone: "go",
  gets: "get", got: "get", gotten: "get",
  makes: "make", made: "make",
  takes: "take", took: "take", taken: "take",
  comes: "come", came: "come",
  sees: "see", saw: "see", seen: "see",
  says: "say", said: "say",
  gives: "give", gave: "give", given: "give",
  finds: "find", found: "find",
  thinks: "think", thought: "think",
  knows: "know", knew: "know", known: "know",
  keeps: "keep", kept: "keep",
  begins: "begin", began: "begin", begun: "begin",
  breaks: "break", broke: "break", broken: "break",
  brings: "bring", brought: "bring",
  builds: "build", built: "build",
  buys: "buy", bought: "buy",
  catches: "catch", caught: "catch",
  chooses: "choose", chose: "choose", chosen: "choose",
  draws: "draw", drew: "draw", drawn: "draw",
  drinks: "drink", drank: "drink", drunk: "drink",
  drives: "drive", drove: "drive", driven: "drive",
  eats: "eat", ate: "eat", eaten: "eat",
  falls: "fall", fell: "fall", fallen: "fall",
  feeds: "feed", fed: "feed",
  feels: "feel", felt: "feel",
  fights: "fight", fought: "fight",
  flies: "fly", flew: "fly", flown: "fly",
  forgets: "forget", forgot: "forget", forgotten: "forget",
  grows: "grow", grew: "grow", grown: "grow",
  hears: "hear", heard: "hear",
  holds: "hold", held: "hold",
  leads: "lead", led: "lead",
  learns: "learn", learnt: "learn",
  leaves: "leave", left: "leave",
  lends: "lend", lent: "lend",
  loses: "lose", lost: "lose",
  means: "mean", meant: "mean",
  meets: "meet", met: "meet",
  pays: "pay", paid: "pay",
  puts: "put",
  reads: "read",
  rides: "ride", rode: "ride", ridden: "ride",
  runs: "run", ran: "run",
  sells: "sell", sold: "sell",
  sends: "send", sent: "send",
  sets: "set",
  shows: "show", showed: "show", shown: "show",
  sings: "sing", sang: "sing", sung: "sing",
  sits: "sit", sat: "sit",
  sleeps: "sleep", slept: "sleep",
  speaks: "speak", spoke: "speak", spoken: "speak",
  spends: "spend", spent: "spend",
  stands: "stand", stood: "stand",
  swims: "swim", swam: "swim", swum: "swim",
  teaches: "teach", taught: "teach",
  tells: "tell", told: "tell",
  throws: "throw", threw: "throw", thrown: "throw",
  understands: "understand", understood: "understand",
  wakes: "wake", woke: "wake", woken: "wake",
  wears: "wear", wore: "wear", worn: "wear",
  wins: "win", won: "win",
  writes: "write", wrote: "write", written: "write",
  better: "good", best: "good", worse: "bad", worst: "bad",
  // 以 ed/eed 结尾的动词原形，不能被当成过去式再砍一刀
  succeed: "succeed", proceed: "proceed", exceed: "exceed",
  feed: "feed", need: "need", speed: "speed", bleed: "bleed", breed: "breed",
  children: "child", people: "people", men: "man", women: "woman",
  teeth: "tooth", feet: "foot", mice: "mouse",
  worse: "badly", further: "far", farther: "far"
};
